### ISSUE TITLE
`get` does not add model to req object

### ISSUE THREAD

**Issue by solidgoldpig** [twg/devour#216]
The client's `get` method does not add the last model to `req` object and therefore other middleware cannot access the model.

The `post` method does add the last model - is it by design that the `get` method does not?

**Comment by tijn** [comment]
I think you're right if you are assuming that this is a mistake. It's really inconsistent for sure.

I searched the commit history and I found [this commit](https://github.com/twg/devour/commit/cb327900326ed2ccb55f9e034111afadd2b1a0b2) where the methods `get` and `post` get introduced; and it already includes a model attribute for `post`; but not for `get`. Sadly there's no explanation in the commit message so I really don't know if this is by design or not.

Anyhow, if you could create a PR that set model too for a `get` which doesn't result in any breaking tests then I would definitely be inclined to merge it. 😄

**Comment by solidgoldpig** [comment]
Resolved in https://github.com/twg/devour/pull/217
